poll/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/',include('pollapp.urls',namespace='pollapps')),
]

pollapp/urls.py
from django.contrib import admin
from django.conf.urls import url


urlpatterns = [
    url(r'^$','pollapp.views.index',name='index'),
    url(r'^(?P<question_id>[0-9]+)/$','pollapp.views.detail',name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$','pollapp.views.results',name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$','pollapp.views.vote',name='vote'),
]

pollapp/models.py
#-*-coding:utf-8-*-
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date>= timezone.now()-datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text

class choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pollapp/views.py
#-*-coding:utf-8-*-

from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from .models import Question,choice
from django.core.urlresolvers import reverse

def index(request):
    latest_question_list=Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list':latest_question_list}
    return render(request,'index.html',context)

def detail(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    print (question)
    return render(request,'detail.html',{'question':question})

def results(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'results.html',{'question':question})


def vote(request,question_id):
    '''
        request.POST['choice'] 以字符串形式返回选择的Choice的ID
        如果在POST数据中没有提供choice，request.POST['choice']将引发一个KeyError。
        上面的代码检查KeyError，如果没有给出choice将重新显示Question表单和一个错误信息。
    '''
    p = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError,choice.DoesNotExist):
        return render(request,'detail.html',{
            'question':p,
            'error_message':'you didn\'t select a choice.',
        })
    else:
        selected_choice.votes+=1
        selected_choice.save()
        #reverse()反向解析 url 'pollapps:results' 找到对应的url地址args传递id形成最终的地址
        return HttpResponseRedirect(reverse('pollapps:results',args=(p.id,)))

templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>title</title>
</head>
<body>
<h2>Question:{{ question.question_text }}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'pollapps:vote' question.id %}" method="post">
    {% csrf_token%}
    {% for choice in question.choice_set.all%}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}"
               value="{{ choice.id }}" />
        <label for ='choice{{ forloop.counter }}'>{{ choice.choice_text }}</label><br/>
    {% endfor %}
<input type="submit" value="Vote" />
</form>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>question list</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!--
           使用命名空间 url 地址
        -->
        <li><a href="{% url 'pollapp:detail' question_id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are avaliable</p>
{% endif %}
</body>
</html>

templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'pollapps:detail' question.id %}">Vote again?</a>
</body>
</html>